### ISSUE TITLE
Suggest pry > irb

### ISSUE THREAD

**Issue by caporta** [learn-co-curriculum/booleans-ruby-readme#11]
In the **boolean operators** section of this module, we suggest they:

> Drop into IRB and use !! (the "double-bang operator") to determine that the string "hi" is truthy:

Would it be better to suggest they "drop into pry" instead of IRB, since we already had students download and use it in the **debugging with pry** module?

**Comment by AnnJohn** [comment]
@SophieDeBenedetto  can you fix and/or close by 8/21

**Comment by SophieDeBenedetto** [comment]
Hi, I'm closing this issue. Pry isn't a good fit here. Pry is good for freezing a ruby program while it runs to examine the inner workings. IRB is good for quick playground  to explore ruby functionality.

**Comment by caporta** [comment]
So Pry's debugging facilities are actually only a portion of what it's capable of. It's also a fully functioning REPL, nearly identical to IRB just with added functionality. Here's a screenshot:

![screen shot 2015-08-19 at 2 12 30 pm](https://cloud.githubusercontent.com/assets/10603933/9364850/5edcf3ae-467c-11e5-9eb5-4755b7d6de4a.png)

Most devs would consider it a more powerful alternative to IRB. Definitely your call whether it's worth replacing IRB with in the track curriculum, but it's definitely much more than just a debugger.

**Comment by SophieDeBenedetto** [comment]
yea, I agree. I think we will leave as is for the time being though.
