### ISSUE TITLE
IRB returns a warning when using !!"string" notation

### ISSUE THREAD

**Issue by dpinkus** [learn-co-curriculum/booleans-ruby-readme#17]
The page says to type !!"hi" to see a true response, but irb warns when this happens; might want to give users a heads-up and explain why it returns such an error.  

2.2.2 :004 > !!"hi"
(irb):4: warning: string literal in condition
 => true 
2.2.2 :005 >

**Comment by AnnJohn** [comment]
@dpinkus Thanks for raising the issue. I'm going to put this issue on icebox for now but we're reviewing and updating all of our curriculum so we'll resolve this issue when we get to this readme. Also, if you want immediate clarification on a lab or lesson, you can use the Ask a Question tool in Learn. But if you're all set with explanations, thanks again for going through our curriculum and raising issues!

**Comment by SophieDeBenedetto** [comment]
@dpinkus just added a note to that effect. thanks for your input!
