### ISSUE TITLE
wrong answer

### ISSUE THREAD

**Issue by zokratez** [learn-co-curriculum/booleans-ruby-readme#26]
number and conditions has the wrong answer on problem  # 15 
 it should be true.

**Comment by pletcher** [comment]
This # 15: `!(10 == 10 && 20 != 10)`? That's definitely false: the `!` operator negates the result of the operations in the parentheses:

`!(10 == 10 && 20 != 10)`
`!(true && 20 != 10)`
`!(true && true)`
`!(true)`
`false`

You can try this out by typing `irb` in your console and entering `!(10 == 10 && 20 != 10)` -- it will return `false`.
