### ISSUE TITLE
Clarification of istrue and isfalse for Quiz

### ISSUE THREAD

**Issue by bging4** [learn-co-curriculum/booleans-ruby-readme#27]
The use of *istrue* and *isfalse* as questions and answers for the quiz can be confusing. Since they are not defined variables, if read literally, the question seems to ask for the return value of the boolean operator with two undefined values.

Example of a question and two answer choices:
> isfalse && istrue
 > istrue
 > is false

To avoid confusion, a short note at the beginning of the quiz would help. For example, immediately after "Let's Practice!":
    _Note: for the quiz, **istrue** represents the boolean `true` or any statement that evaluates to `true` (a truthy statement), and **isfalse**  represents the boolean `false` or any statement that evaluates to `false` (a falsey statement)._

**Comment by AnnJohn** [comment]
thanks @bging4 for raising the issue. We updated istrue and isfalse in the quiz to be just 'true' and 'false'.
