### ISSUE TITLE
I would like to suggest putting the quiz at the end of the lesson.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/booleans-ruby-readme#28]
I think the quiz ought to be at the end of the lesson because the lesson currently has the quiz before the "More Comparison Operators" section. The problem with this is that the quiz uses !=, which is not introduced until the "More Comparison Operators" section.

Another alternative to switching the quiz and the "More Comparison Operators" section around would simply be to introduce != in the section before the quiz.

I realize that this is minor, but it could potentially avoid confusion from students who have not encountered != before. Thanks for looking into this!

Sdcrouse

**Comment by cjbrock** [comment]
Thanks for your suggestion! We'll refactor the quiz to not use the != operator, so it's not confusing. 

// <3 Corinna
