### ISSUE TITLE
I found a bug when navigating to this lesson!

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/booleans-ruby-readme#29]
First of all, this problem seems to be limited only to this specific lesson, but I need to test this out further to be sure. 

The problem is that whenever I navigate to this specific lesson, somehow the title of the page does not read "Boolean Operators" like it's supposed to. Instead, it takes the title of the lesson that I was previously on. Not only that, but it has the navigation bar (Sandbox/Open IDE, Open in GitHub, and Raise an Issue) from the previous lesson as well. 

This is true regardless of how I navigate: by hitting "Next Lesson" from "Booleans and Truthiness in Ruby" (the lesson preceding the Boolean Operators lesson), by hitting the "back" button to go from my current lesson back into "Boolean Operators", and even by using the Curriculum navigation bar to go to "Boolean Operators" when I'm in another lesson.

I tried fixing this by navigating to the "Boolean Operators" lesson when I'm in that lesson, but it will not work. The reason for this is that the navigation bar is ALSO showing that I am still in the other lesson. The only way that I can currently fix this is by hitting "Refresh".

Here's an example of what I'm talking about:
![booleanoperatorsbug1](https://user-images.githubusercontent.com/38870640/43657779-a0f3e2b0-970b-11e8-8847-4dbc5b495908.gif)

Notice above that the lesson content, tab title, and web address are all correct, but the title on the page itself (HTML Basics) is incorrect. And as shown below, the Curriculum navigation menu also shows that I am currently in "HTML Basics" rather than "Boolean Operators":

![booleanoperatorsbug2](https://user-images.githubusercontent.com/38870640/43658085-a843f270-970c-11e8-9905-4b8bc860a248.gif)

I realize that this isn't the biggest bug out there, but it may not be limited to this lesson only. Thanks for checking this out!

Sdcrouse

**Comment by cjbrock** [comment]
That is highly odd. I've submitted a bug report to our product team. Thanks for letting us know!

// <3 Corinna
