### ISSUE TITLE
Error in Operator Operations

### ISSUE THREAD

**Issue by miami917** [learn-co-curriculum/booleans-ruby-readme#31]
Under Operator Operations it says &gt;= represents greater than or equal to. I believe its supposed to say >= instead.

**Comment by lizbur10** [comment]
Hi there,

I'm not able to find the problem. If you can provide further detail about the error, I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Comment by lizbur10** [comment]
Hello again! I was able to find the issue on Canvas and have updated the code. I believe your issue has now been resolved.

Thanks for contributing! 💙
