### ISSUE TITLE
Unable to select answers in quiz

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/booleans-ruby-readme#6]
I attempted to fix the problem by adding some missing back ticks, but it still isn't working for me.

**Comment by SophieDeBenedetto** [comment]
@kvignali quiz answers need to look like this: 

(X)`true` ( )`false`

with space between the parens of wrong answer and text of both answer choices right next to the parens. Now it should be clickable.

**Comment by kvignali** [comment]
I'm still unable to select these. Thinking it might be something bigger going on. Going to run it by the labs team.

**Comment by SophieDeBenedetto** [comment]
yikes you're right! okay thanks.
